modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "TODO"

[[mods]]
modId = "foggy_weather"
version = "${version}"
displayName = "Foggy Weather"
authors = "Me!"
description = '''
TODO
'''
#logoFile = ""

[[dependencies.foggy_weather]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.foggy_weather]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.foggy_weather]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"
